name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main に push されたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Deploy public_html to gh-pages
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          git rm -rf .
          git checkout main -- public_html
          mv public_html/* .
          rmdir public_html
          git add .
          git commit -m "Auto deploy from main to gh-pages"
          git push origin gh-pages --force
